# Generated by Django 5.2.3 on 2025-07-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardingapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errandusers',
            name='referalCode',
        ),
        migrations.RemoveField(
            model_name='shopperusers',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='shopperusers',
            name='password',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='shopperusers',
            name='referrerCode',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='shopperusers',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
