# Generated by Django 5.2.3 on 2025-07-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardingapp', '0002_remove_errandusers_referalcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='errandusers',
            name='password',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
