# Generated by Django 5.2.3 on 2025-08-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboardingapp', '0004_productcategories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCategories',
        ),
    ]
