# Generated by Django 5.2.3 on 2025-08-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardingapp', '0005_delete_productcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='errandusers',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='errandUserProfileImages/'),
        ),
        migrations.AddField(
            model_name='shopperusers',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='customerUserProfileImages/'),
        ),
    ]
