# Generated by Django 5.2.5 on 2025-09-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardingapp', '0006_errandusers_profileimage_shopperusers_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='errandusers',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
