# Generated by Django 5.2.3 on 2025-08-18 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('mtn', 'MTN'), ('glo', 'GLO'), ('airtel', 'AIRTEL'), ('9mobile', '9MOBILE')], default='MTN', max_length=300)),
                ('networdID', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(blank=True, max_length=300, null=True)),
                ('dataPlanType', models.CharField(blank=True, max_length=300, null=True)),
                ('dataQuantity', models.CharField(blank=True, max_length=300, null=True)),
                ('dataCost', models.CharField(blank=True, max_length=300, null=True)),
                ('dataValidity', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.networkid')),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
    ]
