# Generated by Django 5.2.3 on 2025-08-18 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networkid',
            old_name='networdID',
            new_name='networkID',
        ),
    ]
