# Generated by Django 5.2.3 on 2025-08-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_rename_networdid_networkid_networkid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataplans',
            name='dataPlanType',
            field=models.CharField(choices=[('cooporate_gifting', 'Cooporate gifting'), ('sme', 'SME'), ('gifting', 'Gifting'), ('gifting_promo', 'Gifting promo')], default='SME', max_length=300),
        ),
    ]
