# Generated by Django 5.2.3 on 2025-08-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_dataplans_dataplantype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataplans',
            name='productName',
        ),
    ]
