# Generated by Django 5.2.3 on 2025-08-18 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_remove_dataplans_productname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataplans',
            old_name='dataQuantity',
            new_name='productName',
        ),
    ]
