# Generated by Django 5.2.3 on 2025-08-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_rename_dataquantity_dataplans_productname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataplans',
            name='dataValidity',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily'), ('two_days', 'Two Days')], default='monthly', max_length=300),
        ),
    ]
