# Generated by Django 5.2.3 on 2025-08-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_dataplans_datavalidity'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataplans',
            name='planID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
