# Generated by Django 5.2.3 on 2025-08-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_dataplans_planid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityProviders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiaccessname', models.CharField(blank=True, max_length=300, null=True)),
                ('FullName', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
    ]
