# Generated by Django 5.2.3 on 2025-08-07 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(blank=True, max_length=300, null=True)),
                ('categoryImage', models.ImageField(blank=True, null=True, upload_to='categoryimages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(blank=True, max_length=300, null=True)),
                ('productPrice', models.CharField(blank=True, max_length=300, null=True)),
                ('productAvailability', models.CharField(choices=[('In Stock', 'In Stock'), ('Best Seller', 'Best Seller'), ('Low Stock', 'Low Stock'), ('Back Soon', 'Back Soon')], default='In Stock', max_length=300)),
                ('productImage', models.ImageField(blank=True, null=True, upload_to='productimages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('productCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customeruserapp.productcategories')),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoppingListID', models.CharField(blank=True, max_length=300, null=True)),
                ('productPriceAtPurchase', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customeruserapp.products')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
    ]
