# Generated by Django 5.2.3 on 2025-08-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeruserapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistmodel',
            name='assignedErrandPersonID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
