# Generated by Django 5.2.3 on 2025-08-09 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customeruserapp', '0003_shopperassignmenttrackingmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopperassignmenttrackingmodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='shopperassignmenttrackingmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shopperassignmenttrackingmodel',
            name='edited_at',
        ),
    ]
