# Generated by Django 5.2.3 on 2025-08-09 09:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeruserapp', '0004_alter_shopperassignmenttrackingmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopperassignmenttrackingmodel',
            options={'ordering': ['-edited_at', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='shopperassignmenttrackingmodel',
            name='currentAssignedShoppersIDList',
        ),
        migrations.AddField(
            model_name='shopperassignmenttrackingmodel',
            name='assignedShoppersIDList',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='shopperassignmenttrackingmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopperassignmenttrackingmodel',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
