# Generated by Django 5.2.3 on 2025-08-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeruserapp', '0005_alter_shopperassignmenttrackingmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopperAssignTrackingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignedShoppersIDList', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ShopperAssignmentTrackingModel',
        ),
    ]
