# Generated by Django 5.2.3 on 2025-08-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeruserapp', '0006_shopperassigntrackingmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopperassigntrackingmodel',
            name='assignedShoppersIDList',
            field=models.CharField(max_length=300),
        ),
    ]
