# Generated by Django 5.2.3 on 2025-08-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeruserapp', '0007_alter_shopperassigntrackingmodel_assignedshoppersidlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrandUserAssignTrackingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignederranderIDList', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ShopperAssignTrackingModel',
        ),
    ]
