# Generated by Django 5.2.3 on 2025-08-10 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeruserapp', '0009_alter_erranduserassigntrackingmodel_assignederranderidlist'),
        ('onboardingapp', '0005_delete_productcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistmodel',
            name='errandUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='onboardingapp.errandusers'),
        ),
    ]
