# Generated by Django 5.2.3 on 2025-08-11 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeruserapp', '0010_shoppinglistmodel_erranduser'),
        ('onboardingapp', '0005_delete_productcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistmodel',
            name='deliveryStatus',
            field=models.CharField(choices=[('in_store', 'In Store'), ('enroute', 'Enroute'), ('delievered', 'Delievered'), ('failed_delivery', 'Failed Delivery')], default='in_store', max_length=300),
        ),
        migrations.AlterField(
            model_name='shoppinglistmodel',
            name='errandUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onboardingapp.errandusers'),
        ),
    ]
