# Generated by Django 5.2.3 on 2025-08-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeruserapp', '0011_shoppinglistmodel_deliverystatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistmodel',
            name='numberofitems',
            field=models.IntegerField(default=1),
        ),
    ]
