# Generated by Django 5.2.3 on 2025-08-12 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeruserapp', '0012_shoppinglistmodel_numberofitems'),
        ('onboardingapp', '0006_errandusers_profileimage_shopperusers_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistmodel',
            name='itemRequester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='onboardingapp.shopperusers'),
        ),
    ]
