# Generated by Django 5.2.3 on 2025-08-18 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_dataplans_datavalidity'),
        ('customeruserapp', '0013_shoppinglistmodel_itemrequester'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSubscriptionDeliveries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=700, null=True)),
                ('dataDisbursmentStatus', models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='failed', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('dataPlanSelected', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.dataplans')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
    ]
