# Generated by Django 5.2.3 on 2025-08-20 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeruserapp', '0014_datasubscriptiondeliveries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterAirtimePurchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberToRecharge', models.CharField(blank=True, max_length=700, null=True)),
                ('customeRequestID', models.CharField(blank=True, max_length=700, null=True)),
                ('transactionID', models.CharField(blank=True, max_length=700, null=True)),
                ('transactionStatus', models.CharField(blank=True, max_length=700, null=True)),
                ('network', models.CharField(choices=[('mtn', 'MTN'), ('airtel', 'AIRTEL'), ('glo', 'GLO'), ('9mobile', '9MOBILE')], max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
    ]
