# Generated by Django 5.2.3 on 2025-08-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeruserapp', '0016_usermeterrecordsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeterrecordsmodel',
            name='Account_Number',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='usermeterrecordsmodel',
            name='Address',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='usermeterrecordsmodel',
            name='Can_Vend',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='usermeterrecordsmodel',
            name='Customer_Account_Type',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='usermeterrecordsmodel',
            name='Customer_Arrears',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='usermeterrecordsmodel',
            name='Customer_Name',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='usermeterrecordsmodel',
            name='Meter_Type',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='usermeterrecordsmodel',
            name='Min_Purchase_Amount',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='usermeterrecordsmodel',
            name='Minimum_Amount',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='usermeterrecordsmodel',
            name='WrongBillersCode',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
