# Generated by Django 5.2.3 on 2025-08-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeruserapp', '0017_usermeterrecordsmodel_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeterrecordsmodel',
            name='serviceID',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
