# Generated by Django 5.2.3 on 2025-08-20 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeruserapp', '0018_usermeterrecordsmodel_serviceid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermeterrecordsmodel',
            name='amountPaid',
        ),
        migrations.CreateModel(
            name='ElectricityPurchaseRecordsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionId', models.CharField(blank=True, max_length=700, null=True)),
                ('requestId', models.CharField(blank=True, max_length=700, null=True)),
                ('purchasedToken', models.CharField(blank=True, max_length=700, null=True)),
                ('tokenAmount', models.CharField(blank=True, max_length=700, null=True)),
                ('amount', models.CharField(blank=True, max_length=700, null=True)),
                ('purchasedUnits', models.CharField(blank=True, max_length=700, null=True)),
                ('announcement', models.CharField(blank=True, max_length=3000, null=True)),
                ('exchangeReference', models.CharField(blank=True, max_length=3000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('MeterRecords', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customeruserapp.usermeterrecordsmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
    ]
