# Generated by Django 5.2.3 on 2025-08-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeruserapp', '0019_remove_usermeterrecordsmodel_amountpaid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitypurchaserecordsmodel',
            name='customerAddress',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='electricitypurchaserecordsmodel',
            name='customerName',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='electricitypurchaserecordsmodel',
            name='utilityName',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
