# Generated by Django 5.2.3 on 2025-08-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeruserapp', '0020_electricitypurchaserecordsmodel_customeraddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitypurchaserecordsmodel',
            name='mainTokenTax',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
