# Generated by Django 5.2.3 on 2025-08-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeruserapp', '0021_electricitypurchaserecordsmodel_maintokentax'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitypurchaserecordsmodel',
            name='product_name',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
