# Generated by Django 5.2.3 on 2025-08-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeruserapp', '0022_electricitypurchaserecordsmodel_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitypurchaserecordsmodel',
            name='meterType',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
