# Generated by Django 5.2.3 on 2025-08-24 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeruserapp', '0023_electricitypurchaserecordsmodel_metertype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveCableTVPurchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smartcardTVorIUCNumber', models.CharField(blank=True, max_length=3000, null=True)),
                ('product_name', models.CharField(blank=True, max_length=3000, null=True)),
                ('customerName', models.CharField(blank=True, max_length=700, null=True)),
                ('requestId', models.CharField(blank=True, max_length=700, null=True)),
                ('amount', models.CharField(blank=True, max_length=700, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
    ]
