# Generated by Django 5.2.5 on 2025-08-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeruserapp', '0026_successfulldeposites_accesscode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountbalancetracker',
            name='AccountBalance',
            field=models.IntegerField(default=0, max_length=10000),
        ),
    ]
