# Generated by Django 5.2.5 on 2025-09-03 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeruserapp', '0027_alter_useraccountbalancetracker_accountbalance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistmodel',
            name='deliveryStatus',
            field=models.CharField(choices=[('in_store', 'In Store'), ('enroute', 'Enroute'), ('delivered', 'Delivered'), ('failed_delivery', 'Failed Delivery')], default='in_store', max_length=300),
        ),
        migrations.AlterField(
            model_name='useraccountbalancetracker',
            name='AccountBalance',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AvailableUserDeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(blank=True, max_length=500, null=True)),
                ('street', models.CharField(blank=True, max_length=500, null=True)),
                ('houseNumber', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
    ]
