# Generated by Django 5.2.5 on 2025-09-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeruserapp', '0028_alter_shoppinglistmodel_deliverystatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableuserdeliverylocation',
            name='lga',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
