# Generated by Django 5.2.5 on 2025-09-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeruserapp', '0029_availableuserdeliverylocation_lga'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistmodel',
            name='deliveryLocation',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
