# Generated by Django 5.2.5 on 2025-09-07 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeruserapp', '0030_shoppinglistmodel_deliverylocation'),
        ('onboardingapp', '0006_errandusers_profileimage_shopperusers_profileimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickUpState', models.CharField(blank=True, max_length=300, null=True)),
                ('pickUpCountry', models.CharField(blank=True, max_length=300, null=True)),
                ('deliveryState', models.CharField(blank=True, max_length=300, null=True)),
                ('deliveryCountry', models.CharField(blank=True, max_length=300, null=True)),
                ('deliveryTakeOffTime', models.DateTimeField(auto_now_add=True)),
                ('packageDeliveryTime', models.DateTimeField(auto_now_add=True)),
                ('shoppingListID', models.CharField(blank=True, max_length=300, null=True)),
                ('expectedDeliveryDate', models.CharField(blank=True, max_length=300, null=True)),
                ('expectedDeliveryTime', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('errandUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onboardingapp.errandusers')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
    ]
