# Generated by Django 5.2.5 on 2025-09-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeruserapp', '0031_orderstatustracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatustracking',
            name='packageDeliveryTime',
        ),
        migrations.AddField(
            model_name='orderstatustracking',
            name='actualPackageDeliveryDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatustracking',
            name='deliveryTakeOffTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatustracking',
            name='expectedDeliveryDate',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatustracking',
            name='expectedDeliveryTime',
            field=models.CharField(blank=True, null=True),
        ),
    ]
