# Generated by Django 5.2.5 on 2025-09-10 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeruserapp', '0032_remove_orderstatustracking_packagedeliverytime_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityTtile', models.CharField(blank=True, max_length=500, null=True)),
                ('deliveryStatus', models.CharField(blank=True, max_length=500, null=True)),
                ('amountSpent', models.CharField(blank=True, max_length=500, null=True)),
                ('transactionEffect', models.CharField(choices=[('Add', 'add'), ('Subtract', 'Subtract')], default='Add')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
    ]
