# Generated by Django 5.2.5 on 2025-09-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeruserapp', '0033_notificationactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationactivity',
            name='transactionEffect',
            field=models.CharField(choices=[('Add', 'Add'), ('Subtract', 'Subtract')], default='Add'),
        ),
    ]
