# Generated by Django 5.2.5 on 2025-09-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeruserapp', '0034_alter_notificationactivity_transactioneffect'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationactivity',
            name='category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notificationactivity',
            name='month',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
