# Generated by Django 5.2.5 on 2025-09-11 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeruserapp', '0035_notificationactivity_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationactivity',
            name='category',
            field=models.CharField(blank=True, default='all', max_length=500, null=True),
        ),
    ]
