# Generated by Django 5.2.5 on 2025-09-11 01:57

import customeruserapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeruserapp', '0036_alter_notificationactivity_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationactivity',
            name='month',
            field=models.CharField(default=customeruserapp.models.current_month, max_length=2),
        ),
    ]
