# Generated by Django 5.2.5 on 2025-09-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeruserapp', '0037_alter_notificationactivity_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatustracking',
            name='deliveryStatus',
            field=models.CharField(choices=[('in_store', 'In Store'), ('enroute', 'Enroute'), ('delivered', 'Delivered'), ('failed_delivery', 'Failed Delivery')], default='in_store', max_length=300),
        ),
    ]
