# Generated by Django 5.2.5 on 2025-09-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeruserapp', '0038_orderstatustracking_deliverystatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationactivity',
            name='deliveryStatus',
            field=models.CharField(choices=[('successful', 'successful'), ('pending', 'Pending'), ('failed', 'Failed')], default='Pending'),
        ),
    ]
